---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl']

    - name: Install and Enable k3s
      shell: 'curl -sfL https://get.k3s.io | sh -'
#      uri:
#        url: https://get.k3s.io
#        state: present

    - name: Remove ~/.kube file
      file:
        path: ~/.kube
        state: absent

    - name: Remove ~/.kube file
      file:
        path: ~/.kube
        state: present
